# traffic_signs = [
#     "Stop",
#     "Yield",
#     "No Entry",
#     "One Way",
#     "Two Way Traffic",
#     "Pedestrian Crossing",
#     "School Zone",
#     "No Parking",
#     "No Stopping",
#     "Speed Limit 30",
#     "Speed Limit 50",
#     "Speed Limit 70",
#     "Speed Limit 90",
#     "Speed Limit 100",
#     "Speed Limit 120",
#     "End of Speed Limit",
#     "Roundabout",
#     "Keep Left",
#     "Keep Right",
#     "U-Turn",
#     "No U-Turn",
#     "Right Turn Only",
#     "Left Turn Only",
#     "No Left Turn",
#     "No Right Turn",
#     "Merge",
#     "Lane Ends",
#     "Divided Highway",
#     "End Divided Highway",
#     "Traffic Signal Ahead",
#     "Railroad Crossing",
#     "Bicycle Crossing",
#     "Deer Crossing",
#     "Children at Play",
#     "Construction Zone",
#     "Slippery Road",
#     "Falling Rocks",
#     "Steep Hill Down",
#     "Steep Hill Up",
#     "Narrow Bridge",
#     "Low Clearance",
#     "Sharp Turn Right",
#     "Sharp Turn Left",
#     "Winding Road",
#     "Truck Route",
#     "No Trucks",
#     "Weight Limit",
#     "Height Limit",
#     "Width Limit",
#     "Dead End",
#     "No Through Road",
#     "Road Work Ahead",
#     "Detour",
#     "Road Closed",
#     "Cattle Crossing",
#     "Wildlife Crossing",
#     "Hump Bridge",
#     "Speed Bump",
#     "Hospital",
#     "Emergency Services",
#     "Bus Stop",
#     "Taxi Stand",
#     "Ferry",
#     "Tunnel",
#     "Airport",
#     "Motorway",
#     "End Motorway",
#     "Pedestrian Zone",
#     "End Pedestrian Zone",
#     "Parking Area",
#     "Rest Area",
#     "Camping Area",
#     "No Bicycles",
#     "No Pedestrians",
#     "No Motor Vehicles",
#     "No Heavy Vehicles",
#     "No Overtaking",
#     "End No Overtaking",
#     "No Horn",
#     "End No Horn",
#     "No Littering",
#     "No Smoking",
#     "Gas Station",
#     "Electric Charging Station",
#     "Hotel",
#     "Restaurant",
#     "Restroom",
#     "Scenic View",
#     "Information",
#     "Tourist Attraction",
#     "Police",
#     "Fire Station",
#     "Railway Station",
#     "Cyclists",
#     "Roundabout Ahead",
#     "Crossroad",
#     "T-Junction",
#     "Y-Junction",
#     "End of Lane",
#     "Danger Ahead",
#     "Caution",
#     "Frost Warning",
#     "Flood Warning",
#     "Tunnel Ahead",
#     "Bridge Ahead",
#     "No Pedestrian Crossing",
#     "Shared Path",
#     "Animal Warning",
#     "Bump Ahead",
#     "Curves Ahead",
#     "Slow",
#     "Give Way",
#     "Stop Sign Ahead",
#     "School Crossing",
#     "Flagman Ahead"
# ]
traffic_signs = [
    "Stop",
    "Yield",
    "No Entry",
    "One Way",
    "Two Way Traffic",
    "Pedestrian Crossing",
    "School Zone",
    "No Parking",
    "No Stopping",
    "Speed Limit 30",
    "Speed Limit 50",
    "Speed Limit 70",
    "Speed Limit 90",
    "Speed Limit 100",
    "Speed Limit 120",
    "End of Speed Limit",
    "Roundabout",
    "Keep Left",
    "Keep Right",
    "U-Turn",
    "No U-Turn",
    "Right Turn Only",
    "Left Turn Only",
    "No Left Turn",
    "No Right Turn",
    "Merge",
    "Lane Ends",
    "Divided Highway",
    "End Divided Highway",
    "Traffic Signal Ahead",
    "Railroad Crossing",
    "Slippery Road",
    "Falling Rocks",
    "Steep Hill Down",
    "Steep Hill Up",
    "Narrow Bridge",
    "Low Clearance",
    "Sharp Turn Right",
    "Sharp Turn Left",
    "Winding Road",
    "Truck Route",
    "No Trucks",
    "Weight Limit",
    "Height Limit",
    "Width Limit",
    "Dead End",
    "No Through Road",
    "Road Work Ahead",
    "Detour",
    "Road Closed",
    "Cattle Crossing",
    "Speed Bump",
    "Hospital",
    "Emergency Services",
    "Bus Stop",
    "Motorway",
    "End Motorway",
    "Pedestrian Zone",
    "End Pedestrian Zone",
    "Parking Area",
    "Rest Area",
    "No Bicycles",
    "No Pedestrians",
    "No Motor Vehicles",
    "No Overtaking",
    "End No Overtaking",
    "No Horn",
    "End No Horn",
    "No Littering",
    "No Smoking",
    "Gas Station",
    "Electric Charging Station",
    "Hotel",
    "Restaurant",
    "Restroom",
    "Scenic View",
    "Information",
    "Police",
    "Fire Station",
    "Roundabout Ahead",
    "Crossroad",
    "T-Junction",
    "Y-Junction",
    "End of Lane",
    "Caution",
    "Tunnel Ahead",
    "Bridge Ahead",
    "Slow",
    "Give Way",
    "Stop Sign Ahead",
    "School Crossing"
]

print(len(traffic_signs))